server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: catalog-service
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    baseUrl: http://localhost:9411/
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27017
      
info:
  application:
    name: catalog-service
      
eureka:
   instance:
     hostname: localhost
     instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
        
resilience4j:
  circuitbreaker:
    instances:
      movie:
        slidingWindowType: COUNT_BASED
        failureRateThreshold: '40'
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        allowHealthIndicatorToFail: 'false'
        registerHealthIndicator: 'true'
        slidingWindowSize: '10'
        permittedNumberOfCallsInHalfOpenState: '3'
        waitDurationInOpenState: '15000'
      serie:
        slidingWindowType: COUNT_BASED
        failureRateThreshold: '40'
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        allowHealthIndicatorToFail: 'false'
        registerHealthIndicator: 'true'
        slidingWindowSize: '10'
        permittedNumberOfCallsInHalfOpenState: '3'
        waitDurationInOpenState: '15000'
  retry:
    instances:
      movie:
        maxAttempts: '3'
        waitDuration: '1000'
        retryExceptions[0]: feign.FeignException$InternalServerError
      serie:
        maxAttempts: '3'
        waitDuration: '1000'
        retryExceptions[0]: feign.FeignException$InternalServerError
